spring.application.name=task-service

# datasource configuration
spring.mongodb.uri=mongodb://localhost:27017/theDoerTasksDb

#springdoc.packages-to-scan=com.michael.thedoer.taskservice.controller

server.port=0

#ensures different instance id to register multiple instance
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}-${random.value}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Enable health indicator
resilience4j.circuitbreaker.instances.user-service.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.user-service.event-consumer-buffer-size=10

# Sliding window configuration
resilience4j.circuitbreaker.instances.user-service.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.user-service.slidingWindowSize=5

# Failure threshold (percentage)
resilience4j.circuitbreaker.instances.user-service.failureRateThreshold=50

# How long circuit stays OPEN
resilience4j.circuitbreaker.instances.user-service.waitDurationInOpenState=5s

# HALF-OPEN test calls
resilience4j.circuitbreaker.instances.user-service.permittedNumberOfCallsInHalfOpenState=3

resilience4j.circuitbreaker.instances.user-service.automatic-transition-from-open-to-half-open-enabled=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true


# Kafka Server
spring.kafka.bootstrap-servers=localhost:9092

# Consumer group (CHANGE per service)
spring.kafka.consumer.group-id=task-service-group

# Deserializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Trust package for JSON events
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Producer serializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Optional (good practice)
spring.kafka.consumer.auto-offset-reset=earliest

# IMPORTANT FIX
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.michael.thedoer.taskservice.dto.UserCreatedEvent
